// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpYBPWLNmnvG-SyMO4PWJPylj_2BsX1HE',
    appId: '1:184297756321:web:67b57f53fdc0a0d4d242e0',
    messagingSenderId: '184297756321',
    projectId: 'qr-scanner-c634f',
    authDomain: 'qr-scanner-c634f.firebaseapp.com',
    storageBucket: 'qr-scanner-c634f.firebasestorage.app',
    measurementId: 'G-SZTDW7RYB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAce2-ZTvYGRn18e2zTX2LiAaogo9zPkUQ',
    appId: '1:184297756321:android:3850b386837ef7b0d242e0',
    messagingSenderId: '184297756321',
    projectId: 'qr-scanner-c634f',
    storageBucket: 'qr-scanner-c634f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzxtwJ4PmDsSM17i8xu7kwbr9iFLjHr4',
    appId: '1:184297756321:ios:8d96a77d9058ed71d242e0',
    messagingSenderId: '184297756321',
    projectId: 'qr-scanner-c634f',
    storageBucket: 'qr-scanner-c634f.firebasestorage.app',
    iosBundleId: 'com.example.qrReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPzxtwJ4PmDsSM17i8xu7kwbr9iFLjHr4',
    appId: '1:184297756321:ios:8d96a77d9058ed71d242e0',
    messagingSenderId: '184297756321',
    projectId: 'qr-scanner-c634f',
    storageBucket: 'qr-scanner-c634f.firebasestorage.app',
    iosBundleId: 'com.example.qrReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpYBPWLNmnvG-SyMO4PWJPylj_2BsX1HE',
    appId: '1:184297756321:web:55ddaf696c1f069cd242e0',
    messagingSenderId: '184297756321',
    projectId: 'qr-scanner-c634f',
    authDomain: 'qr-scanner-c634f.firebaseapp.com',
    storageBucket: 'qr-scanner-c634f.firebasestorage.app',
    measurementId: 'G-HPTBWG6RVS',
  );
}
